bundler_args: --without development
before_install:
  - gem update --system
  - gem update bundler
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - jruby-9.2.14.0
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
