plugins:
  enable_steam_logins:
    default: false
    validator: "AuthProviderCredentialsValidator"
  steam_web_api_key:
    default: ""
    secret: true
  steam_logins_allow_revoke:
    default: false
